### ISSUE TITLE
Six is removed from Django 3.0

### ISSUE THREAD

**Issue by iamvivekkaushik** [101Loop/drf-addons#7]
As mentioned [here](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis) `six` is removed from Django 3.0.
This package is using six in the [this file](https://github.com/101Loop/drf-addons/blob/master/drfaddons/auth.py). Please update this package with this version of [six](https://pypi.org/project/six/) available at PyPI.

**Comment by iamvivekkaushik** [comment]
Created a pull request #8

**Comment by iamhssingh** [comment]
@iamvivekkaushik In this case, should we not also upgrade the Django's version in `requirements.txt` to 3.x? Is the new format supported in the older version? Is it backward compatible?

**Comment by iamvivekkaushik** [comment]
If someone is using the older version then they will still have the package `six` installed separately, so, it will work.
